# -*- coding: utf-8 -*-
"""AutoCleanAgent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0dimvnO3F8RqWyiHv4-Pihx6j4ChOq4
"""

import os
import pandas as pd

def run_cleaning():
    folder_path = "Titan_Webscrapping/Mouthshut"

    if not os.path.exists(folder_path):
        return "Folder not found."

    xlsx_files = [f for f in os.listdir(folder_path) if f.endswith('.xlsx')]
    if len(xlsx_files) < 2:
        return "Not enough .xlsx files. Exiting."

    columns = ['Name of Reviewer', 'Name_1', 'Location of Reviewer', 'Date of Review',
               'Views on Review', 'Title of Review', 'Detailed Review']

    dataframes = {}

    for file in xlsx_files:
        file_path = os.path.join(folder_path, file)

        try:
            df = pd.read_excel(file_path, header=None, names=columns)
            df.drop(columns=['Name_1'], inplace=True)

            var_name = os.path.splitext(file)[0].replace(" ", "_").lower() + "_df"
            dataframes[var_name] = df

            print(f"Created DataFrame: {var_name}")
        except Exception as e:
            print(f"Error reading {file}: {e}")

    return f"Cleaning complete. {len(dataframes)} file(s) processed."


if __name__ == "__main__":
    result = run_cleaning()
    print(result)

